steps: 
- script: |
    wget -nv https://isabelle.in.tum.de/dist/Isabelle2018.dmg
    hdiutil attach Isabelle2018.dmg
    cp -Rf /Volumes/Isabelle/*.app Isabelle2018/ || :
    hdiutil detach /Volumes/Isabelle
  displayName: "Download and install Isabelle2018"

- script: |
    pwd
    ./Isabelle2018/Isabelle/bin/isabelle build HOL
  displayName: "Isabelle2018 build HOL session"

- task: UniversalPackages@0
  displayName: "Deploying Universal package"
  inputs:
    command: publish
    publishDirectory: 'Isabelle2018/'
    vstsFeedPublish: 'isabelle-hol'
    vstsFeedPackagePublish: 'isabelle-hol-macos'
    packagePublishDescription: 'Isabelle2018 dmg image for macos with pre-built sessions'
    versionOption: custom
    versionPublish: 2018.0.0

