steps: 
- script: |
    wget -nv https://isabelle.in.tum.de/dist/Isabelle2018.dmg
    hdiutil attach Isabelle2018.dmg
    mkdir Isabelle2018
    cp -rf /Volumes/Isabelle/*.app Isabelle2018/
  displayName: "Download and install Isabelle2018"

- script: |
    ./Isabelle2018/Isabelle/bin/isabelle build HOL
  displayName: "Isabelle2018 build HOL session"

- script: |
    sudo hdiutil detach Isabelle2018

- task: UniversalPackages@0
  displayName: "Deploying Universal package"
  inputs:
    command: publish
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    vstsFeedPublish: 'isabelle-hol'
    vstsFeedPackagePublish: 'isabelle-hol-macos'
    packagePublishDescription: 'Isabelle2018 dmg image for macos with pre-built sessions'
    versionOption: custom
    versionPublish: 2018

